# Generated by Django 5.2.5 on 2025-09-17 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=20)),
                ('defects', models.TextField(blank=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('ebay_listing_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amazon_listing_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ebay_category', models.CharField(blank=True, max_length=50, null=True)),
                ('amazon_category', models.CharField(blank=True, max_length=50, null=True)),
                ('listing_status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved for Listing'), ('LISTED', 'Listed on Both Platforms'), ('EBAY_SOLD', 'Sold on eBay'), ('AMAZON_SOLD', 'Sold on Amazon')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SellerContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('pickup_date', models.DateTimeField()),
                ('pickup_address', models.TextField()),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='contact_info', to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
