# Generated by Django 5.2.5 on 2025-09-17 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellercontactinfo',
            options={'verbose_name': 'Legacy Seller Contact Info', 'verbose_name_plural': 'Legacy Seller Contact Info'},
        ),
        migrations.AddField(
            model_name='product',
            name='final_listing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_platform',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='listing_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved for Listing'), ('LISTED', 'Listed on Both Platforms'), ('EBAY_SOLD', 'Sold on eBay'), ('AMAZON_SOLD', 'Sold on Amazon'), ('REMOVED', 'Removed from Listings')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='SubmissionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Admin Review'), ('APPROVED', 'Approved for Processing'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Items Being Listed'), ('COMPLETED', 'All Items Processed')], default='PENDING_REVIEW', max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('pickup_date', models.DateTimeField()),
                ('pickup_address', models.TextField()),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for approval/rejection')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_batches', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BulkListingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(default='BULK_LIST', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partially Completed')], default='PENDING', max_length=20)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('successful_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('submission_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.submissionbatch')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='submission_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.submissionbatch'),
        ),
    ]
