# Generated by Django 5.2.5 on 2025-09-23 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sellercontactinfo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissionbatch',
            name='batch_status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Admin Review'), ('PARTIALLY_PROCESSED', 'Some Products Processed'), ('APPROVED', 'All Products Approved'), ('REJECTED', 'All Products Rejected'), ('PROCESSING', 'Items Being Listed'), ('COMPLETED', 'All Items Processed')], default='PENDING_REVIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='submissionbatch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
