# Generated by Django 5.2.5 on 2025-09-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_listing_url',
            field=models.URLField(blank=True, help_text='Amazon listing URL', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ebay_listing_url',
            field=models.URLField(blank=True, help_text='eBay listing URL', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='amazon_category',
            field=models.CharField(blank=True, help_text='Amazon product category', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='amazon_listing_id',
            field=models.CharField(blank=True, help_text='Amazon ASIN or listing ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ebay_category',
            field=models.CharField(blank=True, help_text='eBay category ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ebay_listing_id',
            field=models.CharField(blank=True, help_text='eBay listing ID', max_length=100, null=True),
        ),
    ]
