# Generated by Django 5.2.5 on 2025-09-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_amazon_listing_url_product_ebay_listing_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulkListingOperation',
        ),
    ]
