# Generated by Django 5.2.5 on 2025-09-27 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_bulklistingoperation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=20)),
                ('defects', models.TextField(blank=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temporary Product',
                'verbose_name_plural': 'Temporary Products',
            },
        ),
        migrations.CreateModel(
            name='TempProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temp_product_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('temp_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.tempproduct')),
            ],
            options={
                'verbose_name': 'Temporary Product Image',
                'verbose_name_plural': 'Temporary Product Images',
                'ordering': ['order'],
            },
        ),
    ]
