# Generated by Django 5.2.5 on 2025-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ebayusertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='listing_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved for Listing'), ('LISTED', 'Listed on Both Platforms'), ('EBAY_SOLD', 'Sold on eBay'), ('AMAZON_SOLD', 'Sold on Amazon'), ('REMOVED', 'Removed from Listings'), ('REJECTED', 'Rejected by Admin')], default='PENDING', max_length=20),
        ),
    ]
