"""
Django settings for auto_market project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-qqkt&s056=d84%(=7$zdvzl%z@ojx+m=)1vcphhd!s*5y@7x5i')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Environment detection
# ENVIRONMENT = os.getenv('ENVIRONMENT', 'production')
# IS_PRODUCTION = ENVIRONMENT == 'production'
# ENABLE_SSL = os.getenv('ENABLE_SSL', 'False').lower() == 'true'

# ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')
ALLOWED_HOSTS = ['*']

# BASE_URL = os.getenv('BASE_URL', 'https://api.bluberryhq.com')
# PUBLIC_BASE_URL = os.getenv('PUBLIC_BASE_URL', 'https://api.bluberryhq.com')

CORS_ALLOWED_ORIGINS = [
    "https://bluberryhq.com",
    "https://www.bluberryhq.com",
]

# CSRF settings for cross-origin requests
# CSRF_TRUSTED_ORIGINS = [
#     'https://bluberryhq.com',
#     'https://www.bluberryhq.com',
#     'https://api.bluberryhq.com',
# ]
# Security settings - completely disabled for local development
# SECURE_SSL_REDIRECT = ENABLE_SSL
# SESSION_COOKIE_SECURE = ENABLE_SSL
# CSRF_COOKIE_SECURE = ENABLE_SSL
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if ENABLE_SSL else None

# X_FRAME_OPTIONS = 'SAMEORIGIN'
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_BROWSER_XSS_FILTER = True

# File upload settings
# FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
# DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
# FILE_UPLOAD_PERMISSIONS = 0o644

# Environment-specific overrides (only if needed in production)
# if IS_PRODUCTION and os.getenv('ENABLE_SSL', 'False').lower() == 'true':
#     SECURE_SSL_REDIRECT = True
#     SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'authentications',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'auto_market.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auto_market.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Additional locations of static files
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',  # Project-level static files
# ]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Static files finders
# STATICFILES_FINDERS = [
#     'django.contrib.staticfiles.finders.FileSystemFinder',
#     'django.contrib.staticfiles.finders.AppDirectoriesFinder',
# ]

# Ensure directories exist
# os.makedirs(STATIC_ROOT, exist_ok=True)
# if STATICFILES_DIRS:
#     for static_dir in STATICFILES_DIRS:
#         os.makedirs(static_dir, exist_ok=True)


# Media files (User uploads like profile pictures and product images)


# Ensure media directory exists
# os.makedirs(MEDIA_ROOT, exist_ok=True)
# os.makedirs(MEDIA_ROOT / 'product_images', exist_ok=True)

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'authentications.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# JWT settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
}

# Email Configuration using Resend (Modern Email Service)
# Resend provides better deliverability than traditional SMTP

RESEND_API_KEY = os.getenv('RESEND_API_KEY', 're_Y66VkqNr_AR4QkbTTF2buCkeCJ7bp9aN2')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@bluberryhq.com')
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', 'alecgold808@gmail.com')

# Use Resend for email sending
EMAIL_BACKEND = 'api.resend_backend.ResendEmailBackend'


# Temporarily allow all origins for testing
# CORS_ALLOW_ALL_ORIGINS = False
# CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
# CORS_ALLOW_CREDENTIALS = True

# CORS_ALLOW_HEADERS = [
#     'accept',
#     'accept-encoding',
#     'authorization',
#     'content-type',
#     'dnt',
#     'origin',
#     'user-agent',
#     'x-csrftoken',
#     'x-requested-with',
# ]
# CORS_ALLOW_METHODS = [
#     'DELETE',
#     'GET',
#     'OPTIONS',
#     'PATCH',
#     'POST',
#     'PUT',
# ]

# Marketplace API Credentials
EBAY_CLIENT_ID = os.getenv('EBAY_CLIENT_ID', 'demo_client_id')
EBAY_CLIENT_SECRET = os.getenv('EBAY_CLIENT_SECRET', 'demo_client_secret')
EBAY_DEV_ID = os.getenv('EBAY_DEV_ID', 'demo_dev_id')
EBAY_APP_NAME = os.getenv('EBAY_APP_NAME', 'DemoApp')
EBAY_SANDBOX = os.getenv('EBAY_SANDBOX', 'False').lower() == 'true'
EBAY_USER_TOKEN = os.getenv('EBAY_USER_TOKEN', None)
EBAY_ENVIRONMENT = os.getenv('EBAY_ENVIRONMENT', 'sandbox')
EBAY_REDIRECT_URI = os.getenv('EBAY_REDIRECT_URI', 'https://bluberryhq.com/api/ebay/callback/')
EBAY_RU_NAME = os.getenv('EBAY_RU_NAME', 'BluBerry-BluBerry-ItemPr-pzocll')
EBAY_FULFILLMENT_POLICY_ID = os.getenv('EBAY_FULFILLMENT_POLICY_ID', None)
EBAY_PAYMENT_POLICY_ID = os.getenv('EBAY_PAYMENT_POLICY_ID', None)
EBAY_RETURN_POLICY_ID = os.getenv('EBAY_RETURN_POLICY_ID', None)

AMAZON_CLIENT_ID = os.getenv('AMAZON_CLIENT_ID', 'demo_amazon_client')
AMAZON_CLIENT_SECRET = os.getenv('AMAZON_CLIENT_SECRET', 'demo_client_secret')
AMAZON_ACCESS_KEY = os.getenv('AMAZON_ACCESS_KEY', 'demo_access_key')
AMAZON_MARKETPLACE_ID = os.getenv('AMAZON_MARKETPLACE_ID', 'ATVPDKIKX0DER')
AMAZON_REGION = os.getenv('AMAZON_REGION', 'us-east-1')
AMAZON_SANDBOX = os.getenv('AMAZON_SANDBOX', 'False').lower() == 'true'

# AWS Credentials for SP-API
AMAZON_AWS_ACCESS_KEY_ID = os.getenv('AMAZON_AWS_ACCESS_KEY_ID', 'demo_aws_key')
AMAZON_AWS_SECRET_ACCESS_KEY = os.getenv('AMAZON_AWS_SECRET_ACCESS_KEY', 'demo_aws_secret')
AMAZON_SELLER_ID = os.getenv('AMAZON_SELLER_ID', 'demo_seller_id')
AMAZON_REFRESH_TOKEN = os.getenv('AMAZON_REFRESH_TOKEN', None)

# Logging Configuration - Simplified
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


